package bean;
// Generated 2017-6-20 0:54:45 by Hibernate Tools 3.5.0.Final

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private String adminId;
	private String password;

	public Admin() {
	}

	public Admin(String adminId, String password) {
		this.adminId = adminId;
		this.password = password;
	}

	public String getAdminId() {
		return this.adminId;
	}

	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
