package bean;
// Generated 2017-6-20 21:05:36 by Hibernate Tools 3.5.0.Final

/**
 * Conditions generated by hbm2java
 */
public class Conditions implements java.io.Serializable {

	private String conditionId;
	private GoodsStatus goodsStatus;
	private String description;

	public Conditions() {
	}

	public Conditions(String conditionId, GoodsStatus goodsStatus, String description) {
		this.conditionId = conditionId;
		this.goodsStatus = goodsStatus;
		this.description = description;
	}

	public String getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(String conditionId) {
		this.conditionId = conditionId;
	}

	public GoodsStatus getGoodsStatus() {
		return this.goodsStatus;
	}

	public void setGoodsStatus(GoodsStatus goodsStatus) {
		this.goodsStatus = goodsStatus;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
