package bean;
// Generated 2017-6-20 1:58:58 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Conditions generated by hbm2java
 */
public class Conditions implements java.io.Serializable {

	private String conditionId;
	private String description;
	private Set goodses = new HashSet(0);

	public Conditions() {
	}

	public Conditions(String conditionId, String description) {
		this.conditionId = conditionId;
		this.description = description;
	}

	public Conditions(String conditionId, String description, Set goodses) {
		this.conditionId = conditionId;
		this.description = description;
		this.goodses = goodses;
	}

	public String getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(String conditionId) {
		this.conditionId = conditionId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getGoodses() {
		return this.goodses;
	}

	public void setGoodses(Set goodses) {
		this.goodses = goodses;
	}

}
