package bean;
// Generated 2017-6-20 0:54:45 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Districtcenter generated by hbm2java
 */
public class Districtcenter implements java.io.Serializable {

	private String centerId;
	private String district;
	private String city;
	private String province;
	private String password;
	private Set goodsesForSendDestrictCenter = new HashSet(0);
	private Set goodsesForReceiveDistrictCenter = new HashSet(0);

	public Districtcenter() {
	}

	public Districtcenter(String centerId) {
		this.centerId = centerId;
	}

	public Districtcenter(String centerId, String district, String city, String province, String password,
			Set goodsesForSendDestrictCenter, Set goodsesForReceiveDistrictCenter) {
		this.centerId = centerId;
		this.district = district;
		this.city = city;
		this.province = province;
		this.password = password;
		this.goodsesForSendDestrictCenter = goodsesForSendDestrictCenter;
		this.goodsesForReceiveDistrictCenter = goodsesForReceiveDistrictCenter;
	}

	public String getCenterId() {
		return this.centerId;
	}

	public void setCenterId(String centerId) {
		this.centerId = centerId;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getGoodsesForSendDestrictCenter() {
		return this.goodsesForSendDestrictCenter;
	}

	public void setGoodsesForSendDestrictCenter(Set goodsesForSendDestrictCenter) {
		this.goodsesForSendDestrictCenter = goodsesForSendDestrictCenter;
	}

	public Set getGoodsesForReceiveDistrictCenter() {
		return this.goodsesForReceiveDistrictCenter;
	}

	public void setGoodsesForReceiveDistrictCenter(Set goodsesForReceiveDistrictCenter) {
		this.goodsesForReceiveDistrictCenter = goodsesForReceiveDistrictCenter;
	}

}
