package bean;
// Generated 2017-6-20 21:05:36 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * GoodsStatus generated by hbm2java
 */
public class GoodsStatus implements java.io.Serializable {

	private GoodsStatusId id;
	private Set conditionses = new HashSet(0);
	private Set goodses = new HashSet(0);

	public GoodsStatus() {
	}

	public GoodsStatus(GoodsStatusId id) {
		this.id = id;
	}

	public GoodsStatus(GoodsStatusId id, Set conditionses, Set goodses) {
		this.id = id;
		this.conditionses = conditionses;
		this.goodses = goodses;
	}

	public GoodsStatusId getId() {
		return this.id;
	}

	public void setId(GoodsStatusId id) {
		this.id = id;
	}

	public Set getConditionses() {
		return this.conditionses;
	}

	public void setConditionses(Set conditionses) {
		this.conditionses = conditionses;
	}

	public Set getGoodses() {
		return this.goodses;
	}

	public void setGoodses(Set goodses) {
		this.goodses = goodses;
	}

}
