package bean;
// Generated 2017-6-20 0:54:45 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Goods generated by hbm2java
 */
public class Goods implements java.io.Serializable {

	private Integer goodsId;
	private Districtcenter districtcenterByReceiveDistrictCenter;
	private Districtcenter districtcenterBySendDestrictCenter;
	private Provincecenter provincecenterBySendProvinceCenter;
	private Provincecenter provincecenterByReceiveProvinceCenter;
	private String senderName;
	private String senderPhone;
	private String senderProvince;
	private String senderCity;
	private String senderAddress;
	private String receiverName;
	private String receiverPhone;
	private String receiverProvince;
	private String receiverCity;
	private String receiverAddress;
	private String status;
	private Set statuses = new HashSet(0);

	public Goods() {
	}

	public Goods(String senderName, String senderPhone, String senderProvince, String senderCity, String senderAddress,
			String receiverName, String receiverPhone, String receiverProvince, String receiverCity,
			String receiverAddress) {
		this.senderName = senderName;
		this.senderPhone = senderPhone;
		this.senderProvince = senderProvince;
		this.senderCity = senderCity;
		this.senderAddress = senderAddress;
		this.receiverName = receiverName;
		this.receiverPhone = receiverPhone;
		this.receiverProvince = receiverProvince;
		this.receiverCity = receiverCity;
		this.receiverAddress = receiverAddress;
	}

	public Goods(Districtcenter districtcenterByReceiveDistrictCenter,
			Districtcenter districtcenterBySendDestrictCenter, Provincecenter provincecenterBySendProvinceCenter,
			Provincecenter provincecenterByReceiveProvinceCenter, String senderName, String senderPhone,
			String senderProvince, String senderCity, String senderAddress, String receiverName, String receiverPhone,
			String receiverProvince, String receiverCity, String receiverAddress, String status, Set statuses) {
		this.districtcenterByReceiveDistrictCenter = districtcenterByReceiveDistrictCenter;
		this.districtcenterBySendDestrictCenter = districtcenterBySendDestrictCenter;
		this.provincecenterBySendProvinceCenter = provincecenterBySendProvinceCenter;
		this.provincecenterByReceiveProvinceCenter = provincecenterByReceiveProvinceCenter;
		this.senderName = senderName;
		this.senderPhone = senderPhone;
		this.senderProvince = senderProvince;
		this.senderCity = senderCity;
		this.senderAddress = senderAddress;
		this.receiverName = receiverName;
		this.receiverPhone = receiverPhone;
		this.receiverProvince = receiverProvince;
		this.receiverCity = receiverCity;
		this.receiverAddress = receiverAddress;
		this.status = status;
		this.statuses = statuses;
	}

	public Integer getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	public Districtcenter getDistrictcenterByReceiveDistrictCenter() {
		return this.districtcenterByReceiveDistrictCenter;
	}

	public void setDistrictcenterByReceiveDistrictCenter(Districtcenter districtcenterByReceiveDistrictCenter) {
		this.districtcenterByReceiveDistrictCenter = districtcenterByReceiveDistrictCenter;
	}

	public Districtcenter getDistrictcenterBySendDestrictCenter() {
		return this.districtcenterBySendDestrictCenter;
	}

	public void setDistrictcenterBySendDestrictCenter(Districtcenter districtcenterBySendDestrictCenter) {
		this.districtcenterBySendDestrictCenter = districtcenterBySendDestrictCenter;
	}

	public Provincecenter getProvincecenterBySendProvinceCenter() {
		return this.provincecenterBySendProvinceCenter;
	}

	public void setProvincecenterBySendProvinceCenter(Provincecenter provincecenterBySendProvinceCenter) {
		this.provincecenterBySendProvinceCenter = provincecenterBySendProvinceCenter;
	}

	public Provincecenter getProvincecenterByReceiveProvinceCenter() {
		return this.provincecenterByReceiveProvinceCenter;
	}

	public void setProvincecenterByReceiveProvinceCenter(Provincecenter provincecenterByReceiveProvinceCenter) {
		this.provincecenterByReceiveProvinceCenter = provincecenterByReceiveProvinceCenter;
	}

	public String getSenderName() {
		return this.senderName;
	}

	public void setSenderName(String senderName) {
		this.senderName = senderName;
	}

	public String getSenderPhone() {
		return this.senderPhone;
	}

	public void setSenderPhone(String senderPhone) {
		this.senderPhone = senderPhone;
	}

	public String getSenderProvince() {
		return this.senderProvince;
	}

	public void setSenderProvince(String senderProvince) {
		this.senderProvince = senderProvince;
	}

	public String getSenderCity() {
		return this.senderCity;
	}

	public void setSenderCity(String senderCity) {
		this.senderCity = senderCity;
	}

	public String getSenderAddress() {
		return this.senderAddress;
	}

	public void setSenderAddress(String senderAddress) {
		this.senderAddress = senderAddress;
	}

	public String getReceiverName() {
		return this.receiverName;
	}

	public void setReceiverName(String receiverName) {
		this.receiverName = receiverName;
	}

	public String getReceiverPhone() {
		return this.receiverPhone;
	}

	public void setReceiverPhone(String receiverPhone) {
		this.receiverPhone = receiverPhone;
	}

	public String getReceiverProvince() {
		return this.receiverProvince;
	}

	public void setReceiverProvince(String receiverProvince) {
		this.receiverProvince = receiverProvince;
	}

	public String getReceiverCity() {
		return this.receiverCity;
	}

	public void setReceiverCity(String receiverCity) {
		this.receiverCity = receiverCity;
	}

	public String getReceiverAddress() {
		return this.receiverAddress;
	}

	public void setReceiverAddress(String receiverAddress) {
		this.receiverAddress = receiverAddress;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getStatuses() {
		return this.statuses;
	}

	public void setStatuses(Set statuses) {
		this.statuses = statuses;
	}

}
