package bean;
// Generated 2017-6-20 14:57:33 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ProvinceCenter generated by hbm2java
 */
public class ProvinceCenter implements java.io.Serializable {

	private Integer centerId;
	private String province;
	private String pwd;
	private Set goodsesForSendProvinceCenter = new HashSet(0);
	private Set goodsesForReceiveProvinceCenter = new HashSet(0);
	private Set transportations = new HashSet(0);

	public ProvinceCenter() {
	}

	public ProvinceCenter(String province, String pwd) {
		this.province = province;
		this.pwd = pwd;
	}

	public ProvinceCenter(String province, String pwd, Set goodsesForSendProvinceCenter,
			Set goodsesForReceiveProvinceCenter, Set transportations) {
		this.province = province;
		this.pwd = pwd;
		this.goodsesForSendProvinceCenter = goodsesForSendProvinceCenter;
		this.goodsesForReceiveProvinceCenter = goodsesForReceiveProvinceCenter;
		this.transportations = transportations;
	}

	public Integer getCenterId() {
		return this.centerId;
	}

	public void setCenterId(Integer centerId) {
		this.centerId = centerId;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public Set getGoodsesForSendProvinceCenter() {
		return this.goodsesForSendProvinceCenter;
	}

	public void setGoodsesForSendProvinceCenter(Set goodsesForSendProvinceCenter) {
		this.goodsesForSendProvinceCenter = goodsesForSendProvinceCenter;
	}

	public Set getGoodsesForReceiveProvinceCenter() {
		return this.goodsesForReceiveProvinceCenter;
	}

	public void setGoodsesForReceiveProvinceCenter(Set goodsesForReceiveProvinceCenter) {
		this.goodsesForReceiveProvinceCenter = goodsesForReceiveProvinceCenter;
	}

	public Set getTransportations() {
		return this.transportations;
	}

	public void setTransportations(Set transportations) {
		this.transportations = transportations;
	}

}
