package bean;
// Generated 2017-6-20 0:54:45 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Provincecenter generated by hbm2java
 */
public class Provincecenter implements java.io.Serializable {

	private String centerId;
	private String province;
	private String password;
	private Set goodsesForSendProvinceCenter = new HashSet(0);
	private Set goodsesForReceiveProvinceCenter = new HashSet(0);
	private Set transportations = new HashSet(0);

	public Provincecenter() {
	}

	public Provincecenter(String centerId) {
		this.centerId = centerId;
	}

	public Provincecenter(String centerId, String province, String password, Set goodsesForSendProvinceCenter,
			Set goodsesForReceiveProvinceCenter, Set transportations) {
		this.centerId = centerId;
		this.province = province;
		this.password = password;
		this.goodsesForSendProvinceCenter = goodsesForSendProvinceCenter;
		this.goodsesForReceiveProvinceCenter = goodsesForReceiveProvinceCenter;
		this.transportations = transportations;
	}

	public String getCenterId() {
		return this.centerId;
	}

	public void setCenterId(String centerId) {
		this.centerId = centerId;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getGoodsesForSendProvinceCenter() {
		return this.goodsesForSendProvinceCenter;
	}

	public void setGoodsesForSendProvinceCenter(Set goodsesForSendProvinceCenter) {
		this.goodsesForSendProvinceCenter = goodsesForSendProvinceCenter;
	}

	public Set getGoodsesForReceiveProvinceCenter() {
		return this.goodsesForReceiveProvinceCenter;
	}

	public void setGoodsesForReceiveProvinceCenter(Set goodsesForReceiveProvinceCenter) {
		this.goodsesForReceiveProvinceCenter = goodsesForReceiveProvinceCenter;
	}

	public Set getTransportations() {
		return this.transportations;
	}

	public void setTransportations(Set transportations) {
		this.transportations = transportations;
	}

}
