package bean;
// Generated 2017-6-20 0:54:45 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status implements java.io.Serializable {

	private String statusId;
	private String description;
	private Set goodses = new HashSet(0);

	public Status() {
	}

	public Status(String statusId, String description) {
		this.statusId = statusId;
		this.description = description;
	}

	public Status(String statusId, String description, Set goodses) {
		this.statusId = statusId;
		this.description = description;
		this.goodses = goodses;
	}

	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getGoodses() {
		return this.goodses;
	}

	public void setGoodses(Set goodses) {
		this.goodses = goodses;
	}

}
