package bean;
// Generated 2017-6-20 21:05:36 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TransportationManagement generated by hbm2java
 */
public class TransportationManagement implements java.io.Serializable {

	private TransportationManagementId id;
	private Set transportations = new HashSet(0);
	private Set provinceCenters = new HashSet(0);

	public TransportationManagement() {
	}

	public TransportationManagement(TransportationManagementId id) {
		this.id = id;
	}

	public TransportationManagement(TransportationManagementId id, Set transportations, Set provinceCenters) {
		this.id = id;
		this.transportations = transportations;
		this.provinceCenters = provinceCenters;
	}

	public TransportationManagementId getId() {
		return this.id;
	}

	public void setId(TransportationManagementId id) {
		this.id = id;
	}

	public Set getTransportations() {
		return this.transportations;
	}

	public void setTransportations(Set transportations) {
		this.transportations = transportations;
	}

	public Set getProvinceCenters() {
		return this.provinceCenters;
	}

	public void setProvinceCenters(Set provinceCenters) {
		this.provinceCenters = provinceCenters;
	}

}
