package bean;
// Generated 2017-6-20 21:05:36 by Hibernate Tools 3.5.0.Final

/**
 * Transportation generated by hbm2java
 */
public class Transportation implements java.io.Serializable {

	private String transportationId;
	private TransportationManagement transportationManagement;
	private String departure;
	private String destintion;

	public Transportation() {
	}

	public Transportation(String transportationId, TransportationManagement transportationManagement, String departure,
			String destintion) {
		this.transportationId = transportationId;
		this.transportationManagement = transportationManagement;
		this.departure = departure;
		this.destintion = destintion;
	}

	public String getTransportationId() {
		return this.transportationId;
	}

	public void setTransportationId(String transportationId) {
		this.transportationId = transportationId;
	}

	public TransportationManagement getTransportationManagement() {
		return this.transportationManagement;
	}

	public void setTransportationManagement(TransportationManagement transportationManagement) {
		this.transportationManagement = transportationManagement;
	}

	public String getDeparture() {
		return this.departure;
	}

	public void setDeparture(String departure) {
		this.departure = departure;
	}

	public String getDestintion() {
		return this.destintion;
	}

	public void setDestintion(String destintion) {
		this.destintion = destintion;
	}

}
